name: Deploy Documentation

on:
  workflow_call:
    inputs:
      directory-project:
        required: true
        type: string
      directory-template:
        required: true
        type: string
      directory-destination:
        required: true
        type: string
      clean-exclude:
        required: false
        type: string
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: python docs.py update-project ${{ inputs.directory-project }} --template-dir=${{ inputs.directory-template }}
      - run: cd ${{ inputs.directory-project }} && mkdocs build -d site/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ inputs.directory-project }}/site
          branch: gh-pages
          target-folder: ${{ inputs.directory-destination }}
          clean-exclude: ${{ inputs.clean-exclude }}
