name: Deploy JMeter HAR Importer Plugin Documentation

on:
  push:
    branches: ["main"]
    paths:
      [
        "template/**",
        "projects/jmeter-har-importer-plugin/docs/**",
        "projects/jmeter-har-importer-plugin/mkdocsLocal.yml",
      ]
  workflow_dispatch:
    # manually triggered

# required for pushing content to a branch
permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/DeployDocumentation.yml
    with:
      directory-project: projects/jmeter-har-importer-plugin
      directory-template: template
      directory-destination: projects/jmeter-har-importer-plugin
